# Generated by Django 4.0.6 on 2022-07-30 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(blank=True, verbose_name=django.utils.timezone.now),
        ),
    ]
